version: "3"
services:
  client:
    container_name: client
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    links:
      - app
  app:
    container_name: app
    restart: always
    build: ./api
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
    restart: always